---
date: "2024-06-06"
sections:
- block: hero
  content:
    cta:
      label: '**Get Started**'
      url: https://hugoblox.com/templates/
    cta_alt:
      label: Ask a question
      url: https://discord.gg/z8wNYzb
    cta_note:
      label: '<div style="text-shadow: none;"><a class="github-button" href="https://github.com/HugoBlox/hugo-blox-builder"
        data-icon="octicon-star" data-size="large" data-show-count="true" aria-label="Star">Star
        Hugo Blox Builder</a></div><div style="text-shadow: none;"><a class="github-button"
        href="https://github.com/HugoBlox/theme-academic-cv" data-icon="octicon-star"
        data-size="large" data-show-count="true" aria-label="Star">Star the Academic
        template</a></div>'
    image:
      filename: hero-academic.png
    text: |-
      **Generated by Hugo Blox Builder - the FREE, Hugo-based open source website builder trusted by 500,000+ sites.**

      **Easily build anything with blocks - no-code required!**

      From landing pages, second brains, and courses to academic resumés, conferences, and tech blogs.

      <!--Custom spacing-->
      <div class="mb-3"></div>
      <!--GitHub Button JS-->
      <script async defer src="https://buttons.github.io/buttons.js"></script>
    title: Hugo Academic Theme
  demo: true
  design:
    background:
      gradient_end: '#1976d2'
      gradient_start: '#004ba0'
      text_color_light: true
- block: about.biography
  content:
    title: Biography
    username: admin
  id: about
- block: skills
  content:
    text: ""
    title: Skills
    username: admin
  design:
    columns: "1"
- block: experience
  content:
    date_format: Jan 2006
    items:
    - company: Durham University
      company_logo: org-du
      company_url: ""
      date_end: ""
      date_start: "2022-01-01"
      location: Durham, UK
      title: Assistant Professor
    - company: Princeton University
      company_logo: org-pu
      company_url: ""
      date_end: "2021-08-31"
      date_start: "2019-06-01"
      location: Princeton, NJ, USA
      title: Postdoctoral Research Associate
    - company: University of Florida
      company_logo: org-uf
      company_url: ""
      date_end: "2019-03-31"
      date_start: "2019-01-01"
      location: Gainesville, FL, USA
      title: Visiting Researcher
    title: Experience
  design:
    columns: "2"
- block: markdown
  content:
    subtitle: ""
    text: '{{< gallery album="demo" >}}'
    title: Gallery
  design:
    columns: "1"
- block: contact
  content:
    address:
      city: Durham
      country: United Kingdom
      country_code: UK
      postcode: "DH1 3LE"
      street:  Department of Biosciences, Durham University
    autolink: true
    coordinates:
      latitude: "54.76505"
      longitude: "-1.57252"
      zoom: 17
    directions: Office 166, Department of Biosciences
    email: rebecca.a.senior@gmail.com
    form:
      formspree:
        id: https://formspree.io/f/rebecca.a.senior@gmail.com
      netlify:
        captcha: false
      provider: netlify
    office_hours: Monday-Friday 09:00 to 17:00 (GMT)
    phone: +44 191 334 1321
    subtitle: null
    title: Contact
  design:
    columns: "2"
  id: contact
title: ""
type: landing
---
